### ISSUE TITLE
Lobby Time is on Cycle upon joining and ignores what it was set to before joining

### ISSUE THREAD

**Issue by blueyCH** [semicola/Rap-Ability-Test#11]
![image_2024-07-02_133027300](https://github.com/semicola/Rap-Ability-Test/assets/121528365/81825268-565e-468c-bf44-6ff8ff9fb903)

Changing the setting does fix this until, of course, you leave and join again

**Comment by skedgyedgy** [comment]
-- Fixed in next update.
