### ISSUE TITLE
trade menu appears to not have a filter

### ISSUE THREAD

**Issue by tlsctf2** [semicola/Rap-Ability-Test#13]
I didn't test this beyond the one instance bc I don't feel like risking my account, but this message got through the trade menu chat while it was filtered in roblox chat
![RobloxScreenShot20240812_223204840](https://github.com/user-attachments/assets/a162f550-f0ab-45d9-a458-0c7a35632943)
(I really hope that image attaches properly)

**Comment by skedgyedgy** [comment]
-- This is your own message. You're reading the text you just typed in yourself. It's displayed before it's even sent to the server.
-- All this feature does is echo Roblox chat messages as they are displayed over a character's head. If it got filtered in the chat, all the other player will see is that filtered message. Roblox just fires the chat message twice for you, once as it was sent and once when the server filters it and sends it to everyone else.
