### ISSUE TITLE
CO-OP bug / Split Screen Mode for soloplay,

### ISSUE THREAD

**Issue by Justanewplaye** [semicola/Rap-Ability-Test#16]
https://drive.google.com/file/d/16l1QgHZK5pPXM-kQ6oCd-iUFvZAs6EY3/view?usp=sharing
This includes the video proof.

**Comment by Justanewplaye** [comment]
Here is clearer proof if you couldn't see the first one.
https://drive.google.com/file/d/1k9mGUoqccvjYGSfg98npYLQLnfmX5AdX/view?usp=sharing

**Comment by skedgyedgy** [comment]
-- Literally what is the bug here. Please put more effort into bug reports.

**Comment by Justanewplaye** [comment]
> -- Literally what is the bug here. Please put more effort into bug reports.

The bug is that you can play multiplayer on one device, I don't know if this was intended, i used keyboard and controller together to make a split screen to play separately.

**Comment by Justanewplaye** [comment]
> -- Literally what is the bug here. Please put more effort into bug reports.

And the game thinks you've played with another player so it does the winning thing, which in my case flings me for losing, as i don't know if you can play as Chester normally with others, but its pretty clear what's on the screen.

**Comment by Justanewplaye** [comment]
> -- Literally what is the bug here. Please put more effort into bug reports.

I can also demonstrate this live when you want to.
