### ISSUE TITLE
Simplify Lobby doesn't seem to work anymore

### ISSUE THREAD

**Issue by MeninoSenpai** [semicola/Rap-Ability-Test#2]
After the Stage Update, activating the option to not change anything in the Lobby.

![RobloxPlayerBeta_h1i9pLZACV](https://github.com/semicola/Rap-Ability-Test/assets/33590078/7c52bbda-58af-4afa-a6ea-909edad32671)

During gameplay, background elements keep unloading and reloading without the old Simplify Lobby.

![RobloxScreenShot20240605_081053410](https://github.com/semicola/Rap-Ability-Test/assets/33590078/8a2f7de8-9d50-4e8f-a8bf-82d7a65ae3d3)

**Comment by skedgyedgy** [comment]
-- Fixed! Won't be live until 0.16.12
