### ISSUE TITLE
C0deN0tes no special note sprites

### ISSUE THREAD

**Issue by HyperBeast43** [semicola/Rap-Ability-Test#3]
the C0deN0tes noteskin doesn't have sprites for the mine/nuke notes, or the bullet notes, which is throwing me off a bit.
currently, mine/nuke notes use the default sprite (not very good for a pixel skin), and bullet notes are pure white... for some reason. you'd think they'd use the default sprites like the mine/nuke notes but no

**Comment by HyperBeast43** [comment]
...jarring. the word i was looking for is jarring

**Comment by skedgyedgy** [comment]
-- Once again, this is not a bug. Please only use this section for bug reports.
