### ISSUE TITLE
Contestant Crusher causes random deaths mid-game

### ISSUE THREAD

**Issue by Largato123** [semicola/Rap-Ability-Test#4]
Being squished from the Contestant Crusher win taunt can cause you to randomly die in-game, which also can result in bans from PVP lobbies.

**Comment by skedgyedgy** [comment]
-- Edited for grammar, please try to be more specific in your bug reports in the future as if I hadn't already had context from the Discord I would have had no clue what this bug report was saying.

**Comment by skedgyedgy** [comment]
-- Regardless, I'm looking into this right now. I doubt I can fix the random dying as it appears to just be Roblox jank, but I am making it so games no longer end when you die and instead a custom reset button will be used. Not going to close this problem until it's confirmed to stop happening in the main game.
