### ISSUE TITLE
Rank/FC mission letters not scrolling properly

### ISSUE THREAD

**Issue by JonnyPopTart** [semicola/Rap-Ability-Test#5]
Using the scroll wheel or bar makes the rank/fc mission letters scroll out of the song selection box
![Screenshot 2024-06-12 144633](https://github.com/semicola/Rap-Ability-Test/assets/123782715/18275a9c-8ba9-46d1-9c44-6383f573956e)

**Comment by skedgyedgy** [comment]
-- This is a Roblox issue.
