### ISSUE TITLE
RAT! VR Normal Lobby First song plays normal but second song always is rated 1.25x

### ISSUE THREAD

**Issue by MultiRelic** [semicola/Rap-Ability-Test#6]
Friend was playing RAT in VR which is something they do all the time for fun... but since the last update they have ran into a problem with the game letting them play the first song normally but after that the game automatically puts it in 1.25x rate and they never selected it.

below is a link to uncut footage playing the first song and showing no modifications to the rate and them respawning and not changing the rate modifier and it automatically making them play 1.25x rate

[Youtube Video of Bug](https://www.youtube.com/watch?v=S1EPucjnLjo&ab_channel=Yokai)

**Comment by skedgyedgy** [comment]
-- Can you try to reproduce this in a video please?
