### ISSUE TITLE
screen/menu bug while in VR RAT!

### ISSUE THREAD

**Issue by MultiRelic** [semicola/Rap-Ability-Test#8]
when loading the game with the new Pride update something has changed and now its unplayable on VR its kinda like a screen inside a screen type of thing its hard to explain without the video

[Bug Video (Youtube)](https://youtu.be/ProT4UiQjsk)

**Comment by zachary523** [comment]
Yep, Happened to me as well, Can confirm this is happening

**Comment by skedgyedgy** [comment]
-- Fixed in next update.
