### ISSUE TITLE
Weird bug with failing/charting??

### ISSUE THREAD

**Issue by OMGemojiXD** [semicola/Rap-Ability-Test#9]
Hey, first time submitting a bug report here. I was playing with a friend and when I failed (it was either my second or third time failing), it just froze my notes playing. Nothing was updating, but I know I didn't crash because I was able to see the judgements of my friend still moving, but nothing was happening. It was really weird, and I have the video here as well for proof (Volume warning, it is a bit loud)

https://github.com/semicola/Rap-Ability-Test/assets/173973615/f411f90f-4a35-4391-a0d4-96556f002390

**Comment by skedgyedgy** [comment]
-- Did the music slow down to a halt? Also what song was this and did you fail to a bullet or just lose health normally.

**Comment by skedgyedgy** [comment]
-- Oh sorry, I didn't realize the video was muted on my end. Ignore the question about it slowing down. In the future please show your logs (F9) because otherwise I can't really investigate this issue at all.

**Comment by OMGemojiXD** [comment]
It didn’t slow down at all, it continued just like normal as shown in the
video

It was the Insane chart for XML Slammer

I believe I hit a death note, or missed a bullet

**Comment by OMGemojiXD** [comment]
Aw shit, i’m sorry!! I forgot that part :(

If it happens again i’ll send another report w/ f9 menu if you want!

**Comment by skedgyedgy** [comment]
-- I'm closing this for now as it hasn't been recreated afaik? If it happens again please do say though!
